/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tela;

import javax.swing.JFrame;

public class App {
    public static void main (String [] args) {

    telaLogin loginTela = new telaLogin();
    
    loginTela.setVisible(true);
    
    loginTela.pack();
    
    loginTela.setLocationRelativeTo(null);
    
    loginTela.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            
    }
}
